accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout')
    ]

retailer/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'retailer'

urlpatterns = [
    path('dashboard/', views.dashboard, name='retdbd'),
    path('inventory/', views.showinvt, name='retinvt'),
    path('profile/', views.showprofile, name='retprof'),
    path('searchpdt/', views.searchpdt, name='srchpdt'),
]

test_run/urls.py
import products.views
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

#=====================================Home page===============================================
def home(request):
    return render(request, 'index.html')
#====================================================, =========================================


urlpatterns = [
    path('admin/', admin.site.urls, name = 'admin'),
    path('', home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('retailer/', include('retailer.urls', namespace='retailer')),
    path('wholesaler/', include('wholesaler.urls', namespace='wholesaler')),
    path('manufacturer/', include('manufacturer.urls', namespace='manufacturer')),
    path('products/', include('products.urls', namespace='products')),

    path('pdtid/<slug:id>', products.views.getpdtbyid),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Atulya | {% block title %} {% endblock title %}</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">

  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'static/plugins/themify-icons/themify-icons.css' %} ">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'static/plugins/slick/slick.css' %} ">
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'static/plugins/Venobox/venobox.css' %} ">
  <!-- aos -->
  <link rel="stylesheet" href="{% static 'static/plugins/aos/aos.css%' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

    {% block head %} {% endblock head %}

</head>

<body>
 {% load static %}

<!-- navigation -->
<section class="fixed-top navigation" style="position: relative">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
      <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- navbar -->
      <div class="collapse navbar-collapse text-center" id="navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#feature">Feature</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="service.html">Service</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
        <a href="{% url 'accounts:register' %}" class="btn btn-primary ml-lg-3 primary-shadow">Register/Login</a>
      </div>
    </nav>
  </div>
</section>
<!-- /navigation -->

    {% block body %}
    {% endblock body %}

    <!-- footer -->
<footer class="footer-section footer" style="background-image: url('{% static 'images/backgrounds/footer-bg.png' %}');">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 text-center text-lg-left mb-4 mb-lg-0">
        <!-- logo -->
        <a href="index.html">
          <img class="img-fluid" src="{% static 'images/logo.png' %}" alt="logo">
        </a>
      </div>
      <!-- footer menu -->
      <nav class="col-lg-8 align-self-center mb-5">
        <ul class="list-inline text-lg-right text-center footer-menu">
          <li class="list-inline-item active"><a href="index.html">Home</a></li>
          <li class="list-inline-item"><a class="page-scroll" href="#feature">Feature</a></li>
          <li class="list-inline-item"><a href="about.html">About</a></li>

          <li class="list-inline-item"><a href="contact.html">Contact</a></li>
        </ul>
      </nav>
      <!-- footer social icon -->
      <nav class="col-12">
        <ul class="list-inline text-lg-right text-center social-icon">
          <li class="list-inline-item">
            <a class="instagram" href="https://instagram.com/bizupreach"><i class="ti-instagram"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="twitter" href="https://twitter.com/bizupreach"><i class="ti-twitter-alt"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="linkedin" href="https://www.linkedin.com/showcase/76116820"><i class="ti-linkedin"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="black" href="mailto:atulyaoff@gmail.com"><i class="ti-email"></i></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- venobox -->
<script src="{% static 'plugins/Venobox/venobox.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>


</body>

{% block javascript %}
{% endblock javascript %}
</html>

templates/hire-us.html
<script>window.location.replace("https://download.themefisher.com/tf-hire.html");</script>

templates/index.html
<!DOCTYPE html>
<html lang="zxx">
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Atulya</title>

  <!-- mobile responsive meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=5.0, minimum-scale=0.86">
  
  <!-- ** Plugins Needed for the Project ** -->
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
  <!-- themefy-icon -->
  <link rel="stylesheet" href="{% static 'static/plugins/themify-icons/themify-icons.css' %} ">
  <!-- slick slider -->
  <link rel="stylesheet" href="{% static 'static/plugins/slick/slick.css' %} ">
  <!-- venobox popup -->
  <link rel="stylesheet" href="{% static 'static/plugins/Venobox/venobox.css' %} ">
  <!-- aos -->
  <link rel="stylesheet" href="{% static 'static/plugins/aos/aos.css%' %}">

  <!-- Main Stylesheet -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  
  <!--Favicon-->
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

</head>

<body>
 {% load static %}

<!-- navigation -->
<section class="fixed-top navigation">
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
      <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- navbar -->
      <div class="collapse navbar-collapse text-center" id="navbar">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="index.html">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#feature">Feature</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="about.html">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="service.html">Service</a>
          </li>
          
          
          <li class="nav-item">
            <a class="nav-link" href="contact.html">Contact</a>
          </li>
        </ul>
        <a href="{% url 'accounts:register' %}" class="btn btn-primary ml-lg-3 primary-shadow">Register/Login</a>
      </div>
    </nav>
  </div>
</section>
<!-- /navigation -->

<!-- hero area -->
<section class="hero-section hero" data-background="" style="background-image:url('{% static 'images/hero-area/banner-bg.png'%}');">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center zindex-1">
        <h1 class="mb-3">Harnessing Handy Technologies</h1>
          <h2 class="mb-3">To Connect Supply Chain Partners</h2>
        <p class="mb-4">Buying & selling on Atulya enables<br>
          automatic updation Of inventory & ledger.</p>
        <a href="service.html" class="btn btn-secondary btn-lg">explore us</a>
        <!-- banner image -->
        <img class="img-fluid w-100 banner-image" src="{% static 'images/hero-area/banner-img.png' %}" alt="banner-img">
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <div id="scene">
    <img class="img-fluid hero-bg-1 up-down-animation" src="{% static 'images/background-shape/feature-bg-2.png' %}" alt="">
    <img class="img-fluid hero-bg-2 left-right-animation" src="{% static 'images/background-shape/seo-ball-1.png' %}" alt="">
    <img class="img-fluid hero-bg-3 left-right-animation" src="{% static 'images/background-shape/seo-half-cycle.png' %}" alt="">
    <img class="img-fluid hero-bg-4 up-down-animation" src="{% static 'images/background-shape/green-dot.png' %}" alt="">
    <img class="img-fluid hero-bg-5 left-right-animation" src="{% static 'images/background-shape/blue-half-cycle.png' %}" alt="">
    <img class="img-fluid hero-bg-6 up-down-animation" src="{% static 'images/background-shape/seo-ball-1.png' %}" alt="">
    <img class="img-fluid hero-bg-7 left-right-animation" src="{% static 'images/background-shape/yellow-triangle.png' %}" alt="">
    <img class="img-fluid hero-bg-8 up-down-animation" src="{% static 'images/background-shape/service-half-cycle.png' %}" alt="">
    <img class="img-fluid hero-bg-9 up-down-animation" src="{% static 'images/background-shape/team-bg-triangle.png' %}" alt="">
  </div>
</section>
<!-- /hero-area -->

<!-- feature -->
<section class="section feature mb-0" id="feature">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-title">Amazing Features</h2>
        <p class="mb-100">Atulya has introduced you some incredible tools to help you take your business online.</p>
      </div>
      <!-- feature item -->
      <div class="col-md-6 mb-80">
        <div class="d-flex feature-item">
          <div>
            <i class="ti-ruler-pencil feature-icon mr-4"></i>
          </div>
          <div>
            <h4>Dynamic Inventory</h4>
            <p>Automatically Inventory management without <br>any complications.</p>
          </div>
        </div>
      </div>
      <!-- feature item -->
      <div class="col-md-6 mb-80">
        <div class="d-flex feature-item">
          <div>
            <i class="ti-layout-cta-left feature-icon mr-4"></i>
          </div>
          <div>
            <h4>Order Management</h4>
            <p>Manage orders hassle-free with smooth <br> operations in real time.</p>
          </div>
        </div>
      </div>
      <!-- feature item -->
      <div class="col-md-6 mb-80">
        <div class="d-flex feature-item">
          <div>
            <i class="ti-harddrives feature-icon mr-4"></i>
          </div>
          <div>
            <h4>Automatic Ledger</h4>
            <p>Embedded into your dashboard which will <br>keep records for all the transactions.</p>
          </div>
        </div>
      </div>
      <!-- feature item -->
      <div class="col-md-6 mb-80">
        <div class="d-flex feature-item">
          <div>
            <i class="ti-bar-chart-alt feature-icon mr-4"></i>
          </div>
          <div>
            <h4>Realtime Analytics</h4>
            <p>We added Analytics for you to monitor sales <br> xand profit in real realtime.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <img class="feature-bg-1 up-down-animation" src="{% static 'images/background-shape/feature-bg-1.png' %}" alt="bg-shape">
  <img class="feature-bg-2 left-right-animation" src="{% static 'images/background-shape/feature-bg-2.png' %}" alt="bg-shape">
</section>
<!-- /feature -->

<!-- marketing -->
<section class="section-lg seo">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="seo-image">
          <img class="img-fluid" src="{% static 'images/marketing/marketing.png' %}" alt="form-img">
        </div>
      </div>
      <div class="col-md-5">
        <h2 class="section-title">A Complete Range Of E-Commerce</h2>
        <p>The world is changing in every fraction of a second,
          and we have incredibly futuristic services for our
          clients as a result. Atulya is unique in that it
          offers a wide range of services. Dynamic inventory
          and ledger with real-time statistics to visualize
          your performance, as well as capabilities to connect
          you to your customers.
        </p>
      </div>
    </div>
  </div>
  <!-- background image -->
  <img class="img-fluid seo-bg" src="{% static 'images/backgrounds/seo-bg.png' %}" alt="seo-bg">
  <!-- background-shape -->
  <img class="seo-bg-shape-1 left-right-animation" src="{% static 'images/background-shape/seo-ball-1.png' %}" alt="bg-shape">
  <img class="seo-bg-shape-2 up-down-animation" src="{% static 'images/background-shape/seo-half-cycle.png' %}" alt="bg-shape">
  <img class="seo-bg-shape-3 left-right-animation" src="{% static 'images/background-shape/seo-ball-2.png' %}" alt="bg-shape">
</section>
<!-- /marketing -->

<!-- service -->
<section class="section-lg service">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-5 order-2 order-md-1">
        <h2 class="section-title">Powerful App to Stand Out</h2>
        <p class="mb-4">This application is developed after seeing
          each and every problem of Indian Retailers and Wholesalers,
          from which you are dealing and all those includes Billing,
          Inventory, Online orders, GST, and more.<br>
          We are dealing with all at once.</p>
        <ul class="pl-0 service-list">
          <li><i class="ti-layout-tab-window text-purple"></i>Responsive on any device</li>
          <li><i class="ti-layout-placeholder text-purple"></i>Easy to operate</li>
          <li><i class="ti-support text-purple"></i>Effective support</li>
        </ul>
      </div>
      <div class="col-md-7 order-1 order-md-2">
        <img class="img-fluid layer-3" src="{% static 'images/service/service.png' %}" alt="service">
      </div>
    </div>
  </div>
  <!-- background image -->
  <img class="img-fluid service-bg" src="{% static 'images/backgrounds/service-bg.png' %}" alt="service-bg">
  <!-- background shapes -->
  <img class="service-bg-shape-1 up-down-animation" src="{% static 'images/background-shape/service-half-cycle.png' %}" alt="background-shape">
  <img class="service-bg-shape-2 left-right-animation" src="{% static 'images/background-shape/feature-bg-2.png' %}" alt="background-shape">
</section>
<!-- /service -->



<!-- Line Break to offer space to newsletter-->
<br> <br> <br> 
<!-- /Line Break to offer space to newsletter-->


<!-- newsletter -->
<section class="newsletter">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Subscribe to our newsletter</h2>
        <p class="mb-5">Receive updates, news and deals</p>
      </div>
      <div class="col-lg-8 col-sm-10 col-12 mx-auto">
        <form action="#">
          <div class="input-wrapper position-relative">
            <input type="email" class="newsletter-form" id="newsletter" placeholder="Enter your email">
            <button type="submit" value="send" class="btn newsletter-btn">subscribe</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- background shapes -->
  <img class="newsletter-bg-shape left-right-animation" src="{% static 'images/background-shape/seo-ball-2.png' %} " alt="background-shape">
</section>
<!-- /newsletter -->

<!-- footer -->
<footer class="footer-section footer" style="background-image: url('{% static 'images/backgrounds/footer-bg.png' %}');">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 text-center text-lg-left mb-4 mb-lg-0">
        <!-- logo -->
        <a href="index.html">
          <img class="img-fluid" src="{% static 'images/logo.png' %}" alt="logo">
        </a>
      </div>
      <!-- footer menu -->
      <nav class="col-lg-8 align-self-center mb-5">
        <ul class="list-inline text-lg-right text-center footer-menu">
          <li class="list-inline-item active"><a href="index.html">Home</a></li>
          <li class="list-inline-item"><a class="page-scroll" href="#feature">Feature</a></li>
          <li class="list-inline-item"><a href="about.html">About</a></li>
          
          <li class="list-inline-item"><a href="contact.html">Contact</a></li>
        </ul>
      </nav>
      <!-- footer social icon -->
      <nav class="col-12">
        <ul class="list-inline text-lg-right text-center social-icon">
          <li class="list-inline-item">
            <a class="instagram" href="https://instagram.com/bizupreach"><i class="ti-instagram"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="twitter" href="https://twitter.com/bizupreach"><i class="ti-twitter-alt"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="linkedin" href="https://www.linkedin.com/showcase/76116820"><i class="ti-linkedin"></i></a>
          </li>
          <li class="list-inline-item">
            <a class="black" href="mailto:atulyaoff@gmail.com"><i class="ti-email"></i></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</footer>
<!-- /footer -->

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- venobox -->
<script src="{% static 'plugins/Venobox/venobox.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock title %}

{% block body %}
    <form action='{% url 'accounts:login' %}' method="POST">
        {% csrf_token %}
        <label for="login_email">Enter Email</label>
        <input type="email" name="login_email" id="login_email">
        <br>
        <label for="Login_password">Enter Password</label>
        <input type="password" name="login_password" id="Login_password">
        <br>
        <input type="submit" value="Login">
    </form>
{% endblock body %}

templates/order_list.html
{% extends 'base.html' %}

{% block title %}
  Order List
{% endblock title %}

{% block body %}
  <form method="post">

  </form>

    <div>
    <table>
        <th>
            <tr>Products</tr>
            <tr>Wholesaler</tr>
            <tr>Quantity</tr>
        </th>
        {% for item in list %}
            <th>
            <tr>{{ item.name }}</tr>
            <tr>{{ item.name }}</tr>
            <tr>{{ item.price }}</tr>
            </th>
        {% endfor %}
    </table>
    {{ list. }}
    </div>
{% endblock body %}

templates/product_addition.html
{% extends 'base.html' %}

{% block title %} Add Products {% endblock title %}

{% block body %}

    <div>
        {% if products is not None %}
            <table>
                <tr>
                    <th>Name</th>
                    <th>Brand</th>
                    <th>price</th>
                </tr>
            {% for item in products %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.brand }}</td>
                    <td>{{ item.price }}</td>
                </tr>

            {% endfor %}
            </table>
        {% endif %}
    </div>

{% endblock body %}

templates/registrationform.html
{% extends 'base.html' %}

{% block title %} Register {% endblock title %}

{% block body %}
    <form action={%url 'accounts:register'%} method="post">
        {% csrf_token %}
        <label for="registration_email" >Enter your Email</label>
        <input type="email" id="registration_email" name="registration_email">
        <label for="type_dropdown" >Select the appropriate type</label>
        <select name="type" id="type_dropdown" >
          <option value="retailer">Retailer</option>
          <option value="wholesaler">Wholesaler</option>
          <option value="manufacturer">Manufacturer</option>
          <option value="admin">Admin</option>
        </select>
        <label for="password_field" >Enter your Password</label>
        <input type="password" id="password_field" name="password_field">
        <input type="submit" value="Register">
    </form>
    <a href="{% url 'accounts:login' %}">
        <button>Login</button>
    </a>
{% endblock body %}

templates/retailer_dashboard.html
{% extends 'base.html' %}

{% block title %} Retailer Dashboard {% endblock title %}

{% block body %}
    <div id="operation_area">
        <h3> {{ user_name }} </h3>
    </div>

{# navigation buttons #}

    <a href="{% url 'accounts:logout' %}">
        <button>Logout</button>
    </a>
    <a href="{% url 'retailer:inventory' %}">
        <button>Inventory</button>
    </a>
    <a href="{% url 'retailer:orderlist' %}" }><button>Order List</button>
    </a>

{#  customers segment   #}

    <div id="customer_orders" style="height: 420px; width: 50%; border:solid 2px">
        <span>Customer Orders</span>
    </div>

    <div id="billing_div" >

    </div>
    <div id="wholesaler_list">

    </div>


    <div id="customer_list">
    </div>
{% endblock body %}

templates/rinvttemplate.html
{% extends 'basedboard.html' %}

{% block title %} Retailer Inventory {% endblock title %}

{% block bodycontent %}
    <div class="row vh-50">
        <div class="w-25">
            <form>
                {% csrf_token %}
                <div class="col">
                    <input type="text" method = 'POST' action="{% url 'retailer:retinvt' %}" class="form-control w-75" name="searchterm" id="pdtsrch">
                    <input type="button" value="Search" class="btn btn-success" id="srchbtn">
                </div>
            </form>
        </div>
        <div id="prddisplay"  class="col-12 col-lg-8 col-xxl-9 d-flex card flex-fill w-75 scrolly">
           <table class="table table-hover my-0">
               <thead>
                <tr>
                    <td>Product Id</td>
                    <td>Product Name</td>
                    <td>MRP</td>
                    <td>Action</td>
                </tr>
               </thead>
               <tbody id="tablebody">
                {#                dynamically from the ajax query below                  #}
               </tbody>
           </table>
        </div>
    </div>

    <div class="col-12 col-lg-8 col-xxl-9 d-flex mr-auto">
        <div class="card flex-fill">
            <div class="card-header">

                <h5 class="card-title mb-0">Latest Projects</h5>
            </div>
            <table class="table table-hover my-0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th class="d-none d-xl-table-cell">Price</th>
                        <th class="d-none d-xl-table-cell">Catagory</th>
                        <th>Status</th>
                        <th class="d-none d-md-table-cell"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in inventory %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td class="d-none d-xl-table-cell">{{ item.price }}</td>
                        <td class="d-none d-xl-table-cell">{{ item.catagory }}</td>
                        <td><span class="badge bg-success">Done</span></td>
                        <td class="d-none d-md-table-cell">Vanessa Tucker</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <form>
        {% csrf_token %}
        {{ addpdtform }}
    </form>
{% endblock bodycontent %}

{% block javascript %}
    <script type="text/javascript">

        var table =  $('#tablebody')
        function populateTable(data){
            var table = "" ;

                for(var i in data){
                    table += "<tr>";
                    table += "<td>"
                            + data[i].id +"</td>"
                            + "<td>" + data[i].name +"</td>"
                            + "<td>" + data[i].mrp +"</td>"
                            + "<td>" + "<button class='btn btn-success'>Add to Inventory</button>" +"</td>" ;
                    table += "</tr>";
		        }

            document.getElementById("tablebody").innerHTML = table;

        }


        $('#srchbtn').click(function(){
            console.log("button Clicked");

            $.ajax
            ({
                type : 'POST',
                url : '{% url 'retailer:srchpdt' %}',
                data : {
                        searchterm:$('#pdtsrch').val(),
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success : function(pdtlist)
                {
                    console.log("success");
                    populateTable(pdtlist);
                },
            });
        });
    </script>
{% endblock javascript %}

templates/store_information.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>store_information</title>
</head>
<body>
    <form method="POST" action="{% url 'retailer:fill_details' %}">
        {% csrf_token %}

        {{ form}}

{#        <label for="retail_store_gst">Enter store GST number</label>#}
{#        <input type="text" name="retail_store_gst" id="retail_store_gst">#}
{##}
{#        <label for="retail_store_pan">Enter store PAN number</label>#}
{#        <input type="text" name="retail_store_pan" id="retail_store_pan">#}
{##}
{#        <label for="retail_store_bank_account">Enter bank account number</label>#}
{#        <input type="text" name="retail_store_bank_account" id="retail_store_bank_account">#}
{##}
{#        <label for="retail_store_name">Enter Retail store name</label>#}
{#        <input type="text" name="retail_store_name" id="retail_store_name">#}
{##}
{#        <label for="retail_store_ifsc">Enter ifsc number</label>#}
{#        <input type="text" name="retail_store_ifsc" id="retail_store_ifsc">#}
{##}
{#        <label for="retail_store_upi_id">Enter UPI ID</label>#}
{#        <input type="text" name="retail_store_upi_id" id="retail_store_upi_id">#}

        <input type="submit" value="Submit Information">
    </form>
</body>
</html>